/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.biblioteca.views;

import ec.edu.ups.biblioteca.models.Prestamo;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class ListaPrestamosView extends javax.swing.JInternalFrame {

    private DefaultTableModel modelo;
    private Locale localizacion;
    private ResourceBundle mensajes;

    public ListaPrestamosView() {
        initComponents();
        cambiarIdioma(new Locale("es", "EC"));
    }

    public void cambiarIdioma(Locale locale) {
        localizacion = locale;
        mensajes = ResourceBundle.getBundle("ec.edu.ups.biblioteca.i18n.mensajes", localizacion);

        setTitle(mensajes.getString("ventana.listaPrestamos"));

        jLabel1.setText(mensajes.getString("encabezado.gestionPrestamos"));

        btnListaPrest.setText(mensajes.getString("boton.listar"));
        btnEliminar.setText(mensajes.getString("boton.eliminar"));
        btnCancelar.setText(mensajes.getString("boton.cancelar"));

        configurarTabla();

        revalidate();
        repaint();
    }

    public JTable getTblPrestamos() {
        return tblPrestamos;
    }

    public void setTblPrestamos(JTable tblPrestamos) {
        this.tblPrestamos = tblPrestamos;
    }

    public JButton getBtnCancelar() {
        return btnCancelar;
    }

    public void setBtnCancelar(JButton btnCancelar) {
        this.btnCancelar = btnCancelar;
    }

    public JButton getBtnEliminar() {
        return btnEliminar;
    }

    public void setBtnEliminar(JButton btnEliminar) {
        this.btnEliminar = btnEliminar;
    }

    public JButton getBtnListaPrest() {
        return btnListaPrest;
    }

    public void setBtnListaPrest(JButton btnListaPrest) {
        this.btnListaPrest = btnListaPrest;
    }

    public void configurarTabla() {
        if (modelo == null) {
            modelo = new DefaultTableModel();
            tblPrestamos.setModel(modelo);
        }

        Object[] columnas = {
            mensajes.getString("tabla.columna.libro"),
            mensajes.getString("tabla.columna.usuario"),
            mensajes.getString("tabla.columna.fechaPrestamo"),
            mensajes.getString("tabla.columna.fechaDevolucion"),
            mensajes.getString("tabla.columna.devuelto")
        };

        modelo.setColumnIdentifiers(columnas);

        tblPrestamos.getColumnModel().getColumn(0).setHeaderValue(mensajes.getString("tabla.columna.libro"));
        tblPrestamos.getColumnModel().getColumn(1).setHeaderValue(mensajes.getString("tabla.columna.usuario"));
        tblPrestamos.getColumnModel().getColumn(2).setHeaderValue(mensajes.getString("tabla.columna.fechaPrestamo"));
        tblPrestamos.getColumnModel().getColumn(3).setHeaderValue(mensajes.getString("tabla.columna.fechaDevolucion"));
        tblPrestamos.getColumnModel().getColumn(4).setHeaderValue(mensajes.getString("tabla.columna.devuelto"));

        tblPrestamos.getTableHeader().revalidate();
        tblPrestamos.getTableHeader().repaint();
        tblPrestamos.repaint();
    }

    public void cargarDatos(List<Prestamo> prestamos) {
        limpiarTabla();

        SimpleDateFormat formatoFecha = new SimpleDateFormat(mensajes.getString("formato.fechaCorta"), localizacion);

        for (Prestamo prestamo : prestamos) {
            String estado;

            if (prestamo.isDevuelto()) {
                estado = mensajes.getString("estado.si");
            } else {
                estado = mensajes.getString("estado.no");
            }

            Object[] fila = {
                prestamo.getLibro().getTitulo(),
                prestamo.getUsuario().getNombre(),
                formatoFecha.format(prestamo.getFechaPrestamo()),
                formatoFecha.format(prestamo.getFechaDevolucion()),
                estado
            };

            modelo.addRow(fila);
        }
    }

    public void limpiarTabla() {
        modelo.setRowCount(0);
    }

    public void mostrarInformacion(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, mensajes.getString("dialogo.titulo.informacion"), JOptionPane.INFORMATION_MESSAGE);
    }

    public int confirmarEliminacion() {
        return JOptionPane.showConfirmDialog(this, mensajes.getString("confirmacion.eliminarPrestamo"), mensajes.getString("dialogo.titulo.eliminacion"), JOptionPane.YES_NO_OPTION);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnListaPrest = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPrestamos = new javax.swing.JTable();
        btnCancelar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setBackground(new java.awt.Color(35, 30, 25));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel3.setBackground(new java.awt.Color(35, 30, 25));

        btnListaPrest.setBackground(new java.awt.Color(209, 161, 95));
        btnListaPrest.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        btnListaPrest.setForeground(new java.awt.Color(35, 30, 25));
        btnListaPrest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/biblioteca/images/controlar (2).png"))); // NOI18N
        btnListaPrest.setText("Listar");
        btnListaPrest.setBorderPainted(false);
        btnListaPrest.setFocusPainted(false);
        btnListaPrest.setIconTextGap(10);
        btnListaPrest.addActionListener(this::btnListaPrestActionPerformed);

        jScrollPane1.setBackground(new java.awt.Color(35, 30, 25));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane1.setForeground(new java.awt.Color(235, 235, 235));

        tblPrestamos.setBackground(new java.awt.Color(35, 30, 25));
        tblPrestamos.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        tblPrestamos.setForeground(new java.awt.Color(235, 235, 235));
        tblPrestamos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPrestamos.setGridColor(new java.awt.Color(51, 40, 28));
        tblPrestamos.setSelectionBackground(new java.awt.Color(209, 161, 95));
        jScrollPane1.setViewportView(tblPrestamos);

        btnCancelar.setBackground(new java.awt.Color(51, 40, 28));
        btnCancelar.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(235, 235, 235));
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/biblioteca/images/deshacer.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorderPainted(false);
        btnCancelar.setFocusPainted(false);
        btnCancelar.setIconTextGap(8);
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        btnEliminar.setBackground(new java.awt.Color(51, 40, 28));
        btnEliminar.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(235, 235, 235));
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/biblioteca/images/papelera-xmark.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setBorderPainted(false);
        btnEliminar.setFocusPainted(false);
        btnEliminar.setIconTextGap(8);
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        jLabel1.setFont(new java.awt.Font("Serif", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(218, 204, 184));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/biblioteca/images/documento (1).png"))); // NOI18N
        jLabel1.setText("Gestión de Prestamos");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jLabel1.setIconTextGap(8);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/biblioteca/images/Adobe Express - file.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCancelar)
                            .addComponent(btnListaPrest)
                            .addComponent(btnEliminar)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(btnListaPrest)
                        .addGap(27, 27, 27)
                        .addComponent(btnCancelar)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new java.awt.GridBagConstraints());

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnListaPrestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaPrestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnListaPrestActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnListaPrest;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPrestamos;
    // End of variables declaration//GEN-END:variables
}
