/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.biblioteca.views;

import ec.edu.ups.biblioteca.models.Usuario;
import java.util.List;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class ListaUsuariosView extends javax.swing.JInternalFrame {

    private DefaultTableModel modelo;
    private Locale localizacion;
    private ResourceBundle mensajes;

    public ListaUsuariosView() {
        initComponents();
        cambiarIdioma(new Locale("es", "EC"));
    }

    public void cambiarIdioma(Locale locale) {
        localizacion = locale;
        mensajes = ResourceBundle.getBundle("ec.edu.ups.biblioteca.i18n.mensajes", localizacion);

        setTitle(mensajes.getString("ventana.listaUsuarios"));

        jLabel1.setText(mensajes.getString("encabezado.gestionUsuarios"));

        btnListaUsu.setText(mensajes.getString("boton.listar"));
        btnEliminar.setText(mensajes.getString("boton.eliminar"));
        btnCancelar.setText(mensajes.getString("boton.cancelar"));

        jLabel2.setText("");

        configurarTabla();

        revalidate();
        repaint();
    }

    public JButton getBtnCancelar() {
        return btnCancelar;
    }

    public void setBtnCancelar(JButton btnCancelar) {
        this.btnCancelar = btnCancelar;
    }

    public JButton getBtnListaUsu() {
        return btnListaUsu;
    }

    public void setBtnListaUsu(JButton btnListaUsu) {
        this.btnListaUsu = btnListaUsu;
    }

    public JButton getBtnEliminar() {
        return btnEliminar;
    }

    public void setBtnEliminar(JButton btnEliminar) {
        this.btnEliminar = btnEliminar;
    }

    public void configurarTabla() {
        if (modelo == null) {
            modelo = new DefaultTableModel();
            tblUsuarios.setModel(modelo);
        }

        Object[] columnas = {
            mensajes.getString("tabla.columna.cedula"),
            mensajes.getString("tabla.columna.nombre"),
            mensajes.getString("tabla.columna.correo")
        };

        modelo.setColumnIdentifiers(columnas);

        tblUsuarios.getColumnModel().getColumn(0).setHeaderValue(mensajes.getString("tabla.columna.cedula"));
        tblUsuarios.getColumnModel().getColumn(1).setHeaderValue(mensajes.getString("tabla.columna.nombre"));
        tblUsuarios.getColumnModel().getColumn(2).setHeaderValue(mensajes.getString("tabla.columna.correo"));

        tblUsuarios.getTableHeader().revalidate();
        tblUsuarios.getTableHeader().repaint();
        tblUsuarios.repaint();
    }

    public void cargarDatos(List<Usuario> usuarios) {
        limpiarTabla();

        for (Usuario usuario : usuarios) {
            Object[] fila = {
                usuario.getCedula(),
                usuario.getNombre(),
                usuario.getCorreo()
            };
            modelo.addRow(fila);
        }
    }

    public JTable getTblUsuarios() {
        return tblUsuarios;
    }

    public void limpiarTabla() {
        modelo.setRowCount(0);
    }

    public void mostrarInformacion(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, mensajes.getString("dialogo.titulo.informacion"), JOptionPane.INFORMATION_MESSAGE);
    }

    public int confirmarEliminacion() {
        return JOptionPane.showConfirmDialog(this, mensajes.getString("confirmacion.eliminarUsuario"), mensajes.getString("dialogo.titulo.eliminacion"), JOptionPane.YES_NO_OPTION);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();
        btnListaUsu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Gestionar Usuarios");

        jPanel16.setBackground(new java.awt.Color(35, 30, 25));
        jPanel16.setLayout(new java.awt.GridBagLayout());

        jPanel17.setBackground(new java.awt.Color(35, 30, 25));

        jScrollPane1.setBackground(new java.awt.Color(35, 30, 25));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane1.setForeground(new java.awt.Color(235, 235, 235));

        tblUsuarios.setBackground(new java.awt.Color(35, 30, 25));
        tblUsuarios.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tblUsuarios.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        tblUsuarios.setForeground(new java.awt.Color(218, 204, 184));
        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblUsuarios.setGridColor(new java.awt.Color(51, 40, 28));
        tblUsuarios.setSelectionBackground(new java.awt.Color(209, 161, 95));
        jScrollPane1.setViewportView(tblUsuarios);

        btnListaUsu.setBackground(new java.awt.Color(209, 161, 95));
        btnListaUsu.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        btnListaUsu.setForeground(new java.awt.Color(35, 30, 25));
        btnListaUsu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/biblioteca/images/controlar (2).png"))); // NOI18N
        btnListaUsu.setText("Listar");
        btnListaUsu.setBorderPainted(false);
        btnListaUsu.setFocusPainted(false);
        btnListaUsu.setIconTextGap(10);
        btnListaUsu.addActionListener(this::btnListaUsuActionPerformed);

        jLabel1.setFont(new java.awt.Font("Serif", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(218, 204, 184));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/biblioteca/images/documento (1).png"))); // NOI18N
        jLabel1.setText("Gestión de Usuarios");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jLabel1.setIconTextGap(8);

        btnCancelar.setBackground(new java.awt.Color(51, 40, 28));
        btnCancelar.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(218, 204, 184));
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/biblioteca/images/deshacer.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorderPainted(false);
        btnCancelar.setFocusPainted(false);
        btnCancelar.setIconTextGap(8);
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        btnEliminar.setBackground(new java.awt.Color(51, 40, 28));
        btnEliminar.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(218, 204, 184));
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/biblioteca/images/deshacer.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setBorderPainted(false);
        btnEliminar.setFocusPainted(false);
        btnEliminar.setIconTextGap(8);
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/biblioteca/images/Adobe Express - file.png"))); // NOI18N
        jLabel2.setText("dwdw");

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCancelar)
                            .addComponent(btnListaUsu)
                            .addComponent(btnEliminar)))
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(5, 5, 5)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(btnListaUsu)
                        .addGap(31, 31, 31)
                        .addComponent(btnCancelar)
                        .addGap(31, 31, 31)
                        .addComponent(btnEliminar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel16.add(jPanel17, new java.awt.GridBagConstraints());

        getContentPane().add(jPanel16, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnListaUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaUsuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnListaUsuActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnListaUsu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblUsuarios;
    // End of variables declaration//GEN-END:variables
}
