/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.biblioteca.views;

import ec.edu.ups.biblioteca.models.Libro;
import java.util.List;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class ListaLibrosView extends javax.swing.JInternalFrame {

    private DefaultTableModel modelo;
    private Locale localizacion;
    private ResourceBundle mensajes;

    public ListaLibrosView() {
        initComponents();
        cambiarIdioma(new Locale("es", "EC"));
    }

    public void cambiarIdioma(Locale locale) {
        localizacion = locale;
        mensajes = ResourceBundle.getBundle("ec.edu.ups.biblioteca.i18n.mensajes", localizacion);

        setTitle(mensajes.getString("ventana.listaLibros"));

        jLabel1.setText(mensajes.getString("encabezado.gestionLibros"));

        btnListarLibros.setText(mensajes.getString("boton.listar"));
        btnEliminar.setText(mensajes.getString("boton.eliminar"));
        btnCancelar1.setText(mensajes.getString("boton.cancelar"));

        configurarTabla();

        revalidate();
        repaint();
    }

    public JButton getBtnCancelar() {
        return btnEliminar;
    }

    public void setBtnCancelar(JButton btnCancelar) {
        this.btnEliminar = btnCancelar;
    }

    public JButton getBtnListarLibros() {
        return btnListarLibros;
    }

    public void setBtnListarLibros(JButton btnListarLibros) {
        this.btnListarLibros = btnListarLibros;
    }

    public JButton getBtnEliminar() {
        return btnEliminar;
    }

    public void setBtnEliminar(JButton btnEliminar) {
        this.btnEliminar = btnEliminar;
    }

     public void configurarTabla() {
        if (modelo == null) {
            modelo = new DefaultTableModel();
            tblLibros.setModel(modelo);
        }

        Object[] columnas = {
            mensajes.getString("tabla.columna.isbn"),
            mensajes.getString("tabla.columna.titulo"),
            mensajes.getString("tabla.columna.autor"),
            mensajes.getString("tabla.columna.anio"),
            mensajes.getString("tabla.columna.categoria"),
            mensajes.getString("tabla.columna.disponible")
        };

        modelo.setColumnIdentifiers(columnas);

        tblLibros.getColumnModel().getColumn(0).setHeaderValue(mensajes.getString("tabla.columna.isbn"));
        tblLibros.getColumnModel().getColumn(1).setHeaderValue(mensajes.getString("tabla.columna.titulo"));
        tblLibros.getColumnModel().getColumn(2).setHeaderValue(mensajes.getString("tabla.columna.autor"));
        tblLibros.getColumnModel().getColumn(3).setHeaderValue(mensajes.getString("tabla.columna.anio"));
        tblLibros.getColumnModel().getColumn(4).setHeaderValue(mensajes.getString("tabla.columna.categoria"));
        tblLibros.getColumnModel().getColumn(5).setHeaderValue(mensajes.getString("tabla.columna.disponible"));

        tblLibros.getTableHeader().revalidate();
        tblLibros.getTableHeader().repaint();
        tblLibros.repaint();
    }

    public void cargarDatos(List<Libro> libros) {
        limpiarTabla();

        for (Libro libro : libros) {
            String disponible = libro.isDisponible()
                    ? mensajes.getString("estado.si") : mensajes.getString("estado.no");

            Object[] fila = {
                libro.getIsbn(),
                libro.getTitulo(),
                libro.getAutor().getNombre(),
                libro.getAnio(),
                libro.getCategoria(),
                disponible
            };
            modelo.addRow(fila);
        }
    }

    public JTable getTblLibros() {
        return tblLibros;
    }

    public void limpiarTabla() {
        modelo.setRowCount(0);
    }

    public void mostrarInformacion(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, mensajes.getString("dialogo.titulo.informacion"), JOptionPane.INFORMATION_MESSAGE);
    }

    public int confirmarEliminacion() {
        return JOptionPane.showConfirmDialog(this, mensajes.getString("confirmacion.eliminarLibro"), mensajes.getString("dialogo.titulo.eliminacion"), JOptionPane.YES_NO_OPTION);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLibros = new javax.swing.JTable();
        btnListarLibros = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        btnCancelar1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Lista Libros");

        jPanel16.setBackground(new java.awt.Color(35, 30, 25));
        jPanel16.setLayout(new java.awt.GridBagLayout());

        jPanel17.setBackground(new java.awt.Color(35, 30, 25));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/biblioteca/images/Adobe Express - file.png"))); // NOI18N

        tblLibros.setBackground(new java.awt.Color(35, 30, 25));
        tblLibros.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        tblLibros.setForeground(new java.awt.Color(218, 204, 184));
        tblLibros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblLibros);

        btnListarLibros.setBackground(new java.awt.Color(209, 161, 95));
        btnListarLibros.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        btnListarLibros.setForeground(new java.awt.Color(35, 30, 25));
        btnListarLibros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/biblioteca/images/controlar (2).png"))); // NOI18N
        btnListarLibros.setText("Listar");
        btnListarLibros.setBorderPainted(false);
        btnListarLibros.setFocusPainted(false);
        btnListarLibros.setIconTextGap(10);
        btnListarLibros.addActionListener(this::btnListarLibrosActionPerformed);

        jLabel1.setFont(new java.awt.Font("Serif", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(218, 204, 184));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/biblioteca/images/documento (1).png"))); // NOI18N
        jLabel1.setText("Gestión de Libros");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jLabel1.setIconTextGap(8);

        btnEliminar.setBackground(new java.awt.Color(51, 40, 28));
        btnEliminar.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(218, 204, 184));
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/biblioteca/images/papelera-xmark.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setBorderPainted(false);
        btnEliminar.setFocusPainted(false);
        btnEliminar.setIconTextGap(8);
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        btnCancelar1.setBackground(new java.awt.Color(51, 40, 28));
        btnCancelar1.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        btnCancelar1.setForeground(new java.awt.Color(218, 204, 184));
        btnCancelar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/biblioteca/images/deshacer.png"))); // NOI18N
        btnCancelar1.setText("Cancelar");
        btnCancelar1.setBorderPainted(false);
        btnCancelar1.setFocusPainted(false);
        btnCancelar1.setIconTextGap(8);
        btnCancelar1.addActionListener(this::btnCancelar1ActionPerformed);

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEliminar)
                            .addComponent(btnListarLibros)
                            .addComponent(btnCancelar1)))
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel2))
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(btnListarLibros)
                        .addGap(30, 30, 30)
                        .addComponent(btnEliminar)
                        .addGap(35, 35, 35)
                        .addComponent(btnCancelar1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel16.add(jPanel17, new java.awt.GridBagConstraints());

        getContentPane().add(jPanel16, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnListarLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarLibrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnListarLibrosActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelar1ActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelar1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar1;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnListarLibros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblLibros;
    // End of variables declaration//GEN-END:variables
}
