/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package ec.edu.ups.biblioteca.views;

/**
 *
 * @author DELL
 */
public class PrincipalView extends javax.swing.JFrame {

    private RegistrarLibroView registrarLibroView;
    private ActualizarRegistrarLibroView actualizarRegistrarLibroView;
    private DevolucionLibroView devolucionLibroView;
    private RegistrarUsuarioView registrarUsuarioView;
    private ActualizarRegistrarUsuarioView actualizarRegistrarUsuarioView;
    private RegistrarPrestamoView registrarPrestamoView;
    private ListaLibrosView listaLibrosView;
    private ListaUsuariosView listaUsuariosView;

    public PrincipalView() {
        initComponents();
        registrarLibroView = new RegistrarLibroView();
        actualizarRegistrarLibroView = new ActualizarRegistrarLibroView();
        devolucionLibroView = new DevolucionLibroView();
        registrarUsuarioView = new RegistrarUsuarioView();
        actualizarRegistrarUsuarioView = new ActualizarRegistrarUsuarioView();
        registrarPrestamoView = new RegistrarPrestamoView();
        listaLibrosView = new ListaLibrosView();
        listaUsuariosView = new ListaUsuariosView();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        libroMenu = new javax.swing.JMenu();
        registrarLibMenuItem = new javax.swing.JMenuItem();
        actualizarLibMenuItem = new javax.swing.JMenuItem();
        devolverLibMenuItem = new javax.swing.JMenuItem();
        usuarioMenu = new javax.swing.JMenu();
        registrarUsuMenuItem = new javax.swing.JMenuItem();
        actualizarUsuMenuItem = new javax.swing.JMenuItem();
        prestamoMenu = new javax.swing.JMenu();
        prestamoMenuItem = new javax.swing.JMenuItem();
        gestionMenu = new javax.swing.JMenu();
        gestionLibrosMenuItem = new javax.swing.JMenuItem();
        gestionUsuMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1024, 720));
        getContentPane().add(desktopPane, java.awt.BorderLayout.CENTER);

        libroMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/biblioteca/images/marcador-del-diario-hacia-abajo.png"))); // NOI18N
        libroMenu.setMnemonic('f');
        libroMenu.setText("Libros");

        registrarLibMenuItem.setMnemonic('o');
        registrarLibMenuItem.setText("Registrar Libro");
        registrarLibMenuItem.addActionListener(this::registrarLibMenuItemActionPerformed);
        libroMenu.add(registrarLibMenuItem);

        actualizarLibMenuItem.setMnemonic('s');
        actualizarLibMenuItem.setText("Actualizar Libros");
        actualizarLibMenuItem.addActionListener(this::actualizarLibMenuItemActionPerformed);
        libroMenu.add(actualizarLibMenuItem);

        devolverLibMenuItem.setMnemonic('a');
        devolverLibMenuItem.setText("Devolver Libro");
        devolverLibMenuItem.addActionListener(this::devolverLibMenuItemActionPerformed);
        libroMenu.add(devolverLibMenuItem);

        menuBar.add(libroMenu);

        usuarioMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/biblioteca/images/agregar-usuario.png"))); // NOI18N
        usuarioMenu.setText("Usuarios");

        registrarUsuMenuItem.setMnemonic('t');
        registrarUsuMenuItem.setText("Registrar Usuario");
        registrarUsuMenuItem.addActionListener(this::registrarUsuMenuItemActionPerformed);
        usuarioMenu.add(registrarUsuMenuItem);

        actualizarUsuMenuItem.setMnemonic('y');
        actualizarUsuMenuItem.setText("Actualizar Usuario");
        actualizarUsuMenuItem.addActionListener(this::actualizarUsuMenuItemActionPerformed);
        usuarioMenu.add(actualizarUsuMenuItem);

        menuBar.add(usuarioMenu);

        prestamoMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/biblioteca/images/importacion-de-archivos.png"))); // NOI18N
        prestamoMenu.setText("Prestamos");

        prestamoMenuItem.setMnemonic('d');
        prestamoMenuItem.setText("Registrar Prestamo");
        prestamoMenuItem.addActionListener(this::prestamoMenuItemActionPerformed);
        prestamoMenu.add(prestamoMenuItem);

        menuBar.add(prestamoMenu);

        gestionMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/biblioteca/images/marcador-del-diario-hacia-abajo.png"))); // NOI18N
        gestionMenu.setMnemonic('f');
        gestionMenu.setText("Gestionar");

        gestionLibrosMenuItem.setMnemonic('o');
        gestionLibrosMenuItem.setText("Gestionar Libros");
        gestionLibrosMenuItem.addActionListener(this::gestionLibrosMenuItemActionPerformed);
        gestionMenu.add(gestionLibrosMenuItem);

        gestionUsuMenuItem.setMnemonic('s');
        gestionUsuMenuItem.setText("Gestionar Usuarios");
        gestionUsuMenuItem.addActionListener(this::gestionUsuMenuItemActionPerformed);
        gestionMenu.add(gestionUsuMenuItem);

        menuBar.add(gestionMenu);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registrarLibMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarLibMenuItemActionPerformed
        if (!registrarLibroView.isVisible()) {
            desktopPane.remove(registrarLibroView);
            registrarLibroView.setVisible(true);
            desktopPane.add(registrarLibroView);
        }
    }//GEN-LAST:event_registrarLibMenuItemActionPerformed

    private void actualizarLibMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarLibMenuItemActionPerformed
        if (!actualizarRegistrarLibroView.isVisible()) {
            desktopPane.remove(actualizarRegistrarLibroView);
            actualizarRegistrarLibroView.setVisible(true);
            desktopPane.add(actualizarRegistrarLibroView);
        }
    }//GEN-LAST:event_actualizarLibMenuItemActionPerformed

    private void devolverLibMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_devolverLibMenuItemActionPerformed
        if (!devolucionLibroView.isVisible()) {
            desktopPane.remove(devolucionLibroView);
            devolucionLibroView.setVisible(true);
            desktopPane.add(devolucionLibroView);
        }
    }//GEN-LAST:event_devolverLibMenuItemActionPerformed

    private void registrarUsuMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarUsuMenuItemActionPerformed
        if (!registrarUsuarioView.isVisible()) {
            desktopPane.remove(registrarUsuarioView);
            registrarUsuarioView.setVisible(true);
            desktopPane.add(registrarUsuarioView);
        }
    }//GEN-LAST:event_registrarUsuMenuItemActionPerformed

    private void actualizarUsuMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarUsuMenuItemActionPerformed
        if (!actualizarRegistrarUsuarioView.isVisible()) {
            desktopPane.remove(actualizarRegistrarUsuarioView);
            actualizarRegistrarUsuarioView.setVisible(true);
            desktopPane.add(actualizarRegistrarUsuarioView);
        }
    }//GEN-LAST:event_actualizarUsuMenuItemActionPerformed

    private void prestamoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prestamoMenuItemActionPerformed
        if (!registrarPrestamoView.isVisible()) {
            desktopPane.remove(registrarPrestamoView);
            registrarPrestamoView.setVisible(true);
            desktopPane.add(registrarPrestamoView);
        }
    }//GEN-LAST:event_prestamoMenuItemActionPerformed

    private void gestionLibrosMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionLibrosMenuItemActionPerformed
        if (!listaLibrosView.isVisible()) {
            desktopPane.remove(listaLibrosView);
            listaLibrosView.setVisible(true);
            desktopPane.add(listaLibrosView);
        }
    }//GEN-LAST:event_gestionLibrosMenuItemActionPerformed

    private void gestionUsuMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionUsuMenuItemActionPerformed
        if (!listaUsuariosView.isVisible()) {
            desktopPane.remove(listaUsuariosView);
            listaUsuariosView.setVisible(true);
            desktopPane.add(listaUsuariosView);
        }
    }//GEN-LAST:event_gestionUsuMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem actualizarLibMenuItem;
    private javax.swing.JMenuItem actualizarUsuMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem devolverLibMenuItem;
    private javax.swing.JMenuItem gestionLibrosMenuItem;
    private javax.swing.JMenu gestionMenu;
    private javax.swing.JMenuItem gestionUsuMenuItem;
    private javax.swing.JMenu libroMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu prestamoMenu;
    private javax.swing.JMenuItem prestamoMenuItem;
    private javax.swing.JMenuItem registrarLibMenuItem;
    private javax.swing.JMenuItem registrarUsuMenuItem;
    private javax.swing.JMenu usuarioMenu;
    // End of variables declaration//GEN-END:variables

}
