/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package ec.edu.ups.biblioteca.views;

import ec.edu.ups.biblioteca.controllers.BibliotecaController;
import ec.edu.ups.biblioteca.dao.BibliotecaDAO;
import ec.edu.ups.biblioteca.dao.BibliotecaDAOMemoria;

/**
 *
 * @author DELL
 */
public class PrincipalView extends javax.swing.JFrame {

    private RegistrarAutorView registrarAutorView;
    private RegistrarLibroView registrarLibroView;
    private ActualizarRegistrarLibroView actualizarRegistrarLibroView;
    private DevolucionLibroView devolucionLibroView;
    private RegistrarUsuarioView registrarUsuarioView;
    private ActualizarRegistrarUsuarioView actualizarRegistrarUsuarioView;
    private RegistrarPrestamoView registrarPrestamoView;
    private ListaLibrosView listaLibrosView;
    private ListaUsuariosView listaUsuariosView;
    private ListaPrestamosView listaPrestamosView;
    private BibliotecaController bibliotecaController;

    public PrincipalView() {
        initComponents();
        registrarAutorView = new RegistrarAutorView();
        registrarLibroView = new RegistrarLibroView();
        actualizarRegistrarLibroView = new ActualizarRegistrarLibroView();
        devolucionLibroView = new DevolucionLibroView();
        registrarUsuarioView = new RegistrarUsuarioView();
        actualizarRegistrarUsuarioView = new ActualizarRegistrarUsuarioView();
        registrarPrestamoView = new RegistrarPrestamoView();
        listaLibrosView = new ListaLibrosView();
        listaUsuariosView = new ListaUsuariosView();
        listaPrestamosView = new ListaPrestamosView();

        BibliotecaDAO bibliotecaDAO = new BibliotecaDAOMemoria();
        bibliotecaController = new BibliotecaController(registrarAutorView, registrarLibroView, registrarUsuarioView, actualizarRegistrarLibroView, actualizarRegistrarUsuarioView, registrarPrestamoView, devolucionLibroView, listaLibrosView, listaUsuariosView, listaPrestamosView, bibliotecaDAO);

        this.setJMenuBar(null);

        desktopPane.add(menuBar);

        menuBar.setBounds(0, 160, 2000, 70);

        javax.swing.border.Border espaciado = javax.swing.BorderFactory.createEmptyBorder(0, 25, 0, 25);

        libroMenu.setBorder(espaciado);
        usuarioMenu.setBorder(espaciado);
        prestamoMenu.setBorder(espaciado);
        gestionMenu.setBorder(espaciado);

        javax.swing.JPanel panelTitulo = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                g.setColor(new java.awt.Color(20, 20, 20, 150));
                g.fillRect(0, 0, getWidth(), getHeight());
            }
        };
        panelTitulo.setLayout(null);
        panelTitulo.setOpaque(false);
        panelTitulo.setBounds(20, 0, 800, 150);
        desktopPane.add(panelTitulo, 0);

        // Sacamos los labels del título del desktopPane y los metemos dentro
        // del panelTitulo, con las mismas coordenadas de antes pero relativas al panel.
        desktopPane.remove(jLabel1);
        desktopPane.remove(jLabel2);
        desktopPane.remove(jLabel3);
        panelTitulo.add(jLabel3);
        panelTitulo.add(jLabel1);
        panelTitulo.add(jLabel2);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new ec.edu.ups.biblioteca.views.EscritorioFondo();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar() {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                // El color 30, 30, 30 es el gris oscuro y 180 es el nivel de cristal ahumado
                g.setColor(new java.awt.Color(30, 30, 30, 180));
                g.fillRect(0, 0, getWidth(), getHeight());
                super.paintComponent(g);
            }
        };
        libroMenu = new javax.swing.JMenu();
        registrarAutorLibMenuItem = new javax.swing.JMenuItem();
        registrarLibMenuItem = new javax.swing.JMenuItem();
        actualizarLibMenuItem = new javax.swing.JMenuItem();
        devolverLibMenuItem = new javax.swing.JMenuItem();
        usuarioMenu = new javax.swing.JMenu();
        registrarUsuMenuItem = new javax.swing.JMenuItem();
        actualizarUsuMenuItem = new javax.swing.JMenuItem();
        prestamoMenu = new javax.swing.JMenu();
        prestamoMenuItem = new javax.swing.JMenuItem();
        gestionMenu = new javax.swing.JMenu();
        gestionLibrosMenuItem = new javax.swing.JMenuItem();
        gestionUsuMenuItem = new javax.swing.JMenuItem();
        gestionPrestamosMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1024, 720));

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(234, 224, 200));
        jLabel2.setText("Aguilar-Tello-Uzhca");
        desktopPane.add(jLabel2);
        jLabel2.setBounds(160, 50, 530, 62);

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(229, 184, 11));
        jLabel1.setText("BIBLIOTECA");
        jLabel1.setIconTextGap(8);
        desktopPane.add(jLabel1);
        jLabel1.setBounds(160, 10, 340, 50);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/biblioteca/images/biblioteca-publica (2).png"))); // NOI18N
        desktopPane.add(jLabel3);
        jLabel3.setBounds(20, 10, 140, 130);

        getContentPane().add(desktopPane, java.awt.BorderLayout.CENTER);

        menuBar.setBackground(new java.awt.Color(30, 30, 30));
        menuBar.setBorder(null);
        menuBar.setBorderPainted(false);
        menuBar.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        menuBar.setMargin(new java.awt.Insets(5, 5, 10, 10));

        libroMenu.setBackground(new java.awt.Color(234, 224, 200));
        libroMenu.setForeground(new java.awt.Color(234, 224, 200));
        libroMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/biblioteca/images/libro-marcador.png"))); // NOI18N
        libroMenu.setMnemonic('f');
        libroMenu.setText("Libros");
        libroMenu.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        libroMenu.setIconTextGap(14);
        libroMenu.setMargin(new java.awt.Insets(25, 0, 25, 0));

        registrarAutorLibMenuItem.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        registrarAutorLibMenuItem.setForeground(new java.awt.Color(234, 224, 200));
        registrarAutorLibMenuItem.setText("Registrar Autor");
        registrarAutorLibMenuItem.addActionListener(this::registrarAutorLibMenuItemActionPerformed);
        libroMenu.add(registrarAutorLibMenuItem);

        registrarLibMenuItem.setBackground(new java.awt.Color(40, 40, 40));
        registrarLibMenuItem.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        registrarLibMenuItem.setForeground(new java.awt.Color(234, 224, 200));
        registrarLibMenuItem.setMnemonic('o');
        registrarLibMenuItem.setText("Registrar Libro");
        registrarLibMenuItem.setMargin(new java.awt.Insets(5, 10, 5, 10));
        registrarLibMenuItem.addActionListener(this::registrarLibMenuItemActionPerformed);
        libroMenu.add(registrarLibMenuItem);

        actualizarLibMenuItem.setBackground(new java.awt.Color(40, 40, 40));
        actualizarLibMenuItem.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        actualizarLibMenuItem.setForeground(new java.awt.Color(234, 224, 200));
        actualizarLibMenuItem.setMnemonic('s');
        actualizarLibMenuItem.setText("Actualizar Libros");
        actualizarLibMenuItem.setMargin(new java.awt.Insets(5, 10, 5, 10));
        actualizarLibMenuItem.addActionListener(this::actualizarLibMenuItemActionPerformed);
        libroMenu.add(actualizarLibMenuItem);

        devolverLibMenuItem.setBackground(new java.awt.Color(40, 40, 40));
        devolverLibMenuItem.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        devolverLibMenuItem.setForeground(new java.awt.Color(234, 224, 200));
        devolverLibMenuItem.setMnemonic('a');
        devolverLibMenuItem.setText("Devolver Libro");
        devolverLibMenuItem.setMargin(new java.awt.Insets(5, 10, 5, 10));
        devolverLibMenuItem.addActionListener(this::devolverLibMenuItemActionPerformed);
        libroMenu.add(devolverLibMenuItem);

        menuBar.add(libroMenu);

        usuarioMenu.setForeground(new java.awt.Color(234, 224, 200));
        usuarioMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/biblioteca/images/agregar-usuario (1).png"))); // NOI18N
        usuarioMenu.setText("Usuarios");
        usuarioMenu.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        usuarioMenu.setIconTextGap(14);
        usuarioMenu.setMargin(new java.awt.Insets(25, 0, 25, 0));

        registrarUsuMenuItem.setBackground(new java.awt.Color(40, 40, 40));
        registrarUsuMenuItem.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        registrarUsuMenuItem.setForeground(new java.awt.Color(234, 224, 200));
        registrarUsuMenuItem.setMnemonic('t');
        registrarUsuMenuItem.setText("Registrar Usuario");
        registrarUsuMenuItem.setMargin(new java.awt.Insets(5, 10, 5, 10));
        registrarUsuMenuItem.addActionListener(this::registrarUsuMenuItemActionPerformed);
        usuarioMenu.add(registrarUsuMenuItem);

        actualizarUsuMenuItem.setBackground(new java.awt.Color(40, 40, 40));
        actualizarUsuMenuItem.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        actualizarUsuMenuItem.setForeground(new java.awt.Color(234, 224, 200));
        actualizarUsuMenuItem.setMnemonic('y');
        actualizarUsuMenuItem.setText("Actualizar Usuario");
        actualizarUsuMenuItem.setMargin(new java.awt.Insets(5, 10, 5, 10));
        actualizarUsuMenuItem.addActionListener(this::actualizarUsuMenuItemActionPerformed);
        usuarioMenu.add(actualizarUsuMenuItem);

        menuBar.add(usuarioMenu);

        prestamoMenu.setForeground(new java.awt.Color(234, 224, 200));
        prestamoMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/biblioteca/images/pedir-prestado (1).png"))); // NOI18N
        prestamoMenu.setText("Prestamos");
        prestamoMenu.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        prestamoMenu.setIconTextGap(14);
        prestamoMenu.setMargin(new java.awt.Insets(25, 0, 25, 0));

        prestamoMenuItem.setBackground(new java.awt.Color(40, 40, 40));
        prestamoMenuItem.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        prestamoMenuItem.setForeground(new java.awt.Color(234, 224, 200));
        prestamoMenuItem.setMnemonic('d');
        prestamoMenuItem.setText("Registrar Prestamo");
        prestamoMenuItem.setMargin(new java.awt.Insets(5, 10, 5, 10));
        prestamoMenuItem.addActionListener(this::prestamoMenuItemActionPerformed);
        prestamoMenu.add(prestamoMenuItem);

        menuBar.add(prestamoMenu);

        gestionMenu.setForeground(new java.awt.Color(234, 224, 200));
        gestionMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/biblioteca/images/procesando-orden (1).png"))); // NOI18N
        gestionMenu.setMnemonic('f');
        gestionMenu.setText("Listados");
        gestionMenu.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        gestionMenu.setIconTextGap(14);
        gestionMenu.setMargin(new java.awt.Insets(25, 0, 25, 0));

        gestionLibrosMenuItem.setBackground(new java.awt.Color(40, 40, 40));
        gestionLibrosMenuItem.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        gestionLibrosMenuItem.setForeground(new java.awt.Color(234, 224, 200));
        gestionLibrosMenuItem.setMnemonic('o');
        gestionLibrosMenuItem.setText("Listados de Libros");
        gestionLibrosMenuItem.setMargin(new java.awt.Insets(5, 10, 5, 10));
        gestionLibrosMenuItem.addActionListener(this::gestionLibrosMenuItemActionPerformed);
        gestionMenu.add(gestionLibrosMenuItem);

        gestionUsuMenuItem.setBackground(new java.awt.Color(40, 40, 40));
        gestionUsuMenuItem.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        gestionUsuMenuItem.setForeground(new java.awt.Color(234, 224, 200));
        gestionUsuMenuItem.setMnemonic('s');
        gestionUsuMenuItem.setText("Listrados de Usuarios");
        gestionUsuMenuItem.setMargin(new java.awt.Insets(5, 10, 5, 10));
        gestionUsuMenuItem.addActionListener(this::gestionUsuMenuItemActionPerformed);
        gestionMenu.add(gestionUsuMenuItem);

        gestionPrestamosMenuItem.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        gestionPrestamosMenuItem.setForeground(new java.awt.Color(234, 224, 200));
        gestionPrestamosMenuItem.setText("Listados de Prestamos");
        gestionPrestamosMenuItem.addActionListener(this::gestionPrestamosMenuItemActionPerformed);
        gestionMenu.add(gestionPrestamosMenuItem);

        menuBar.add(gestionMenu);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registrarLibMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarLibMenuItemActionPerformed
        if (!registrarLibroView.isVisible()) {
            desktopPane.remove(registrarLibroView);
            registrarLibroView.setVisible(true);
            desktopPane.add(registrarLibroView);
        }
    }//GEN-LAST:event_registrarLibMenuItemActionPerformed

    private void actualizarLibMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarLibMenuItemActionPerformed
        if (!actualizarRegistrarLibroView.isVisible()) {
            desktopPane.remove(actualizarRegistrarLibroView);
            actualizarRegistrarLibroView.setVisible(true);
            desktopPane.add(actualizarRegistrarLibroView);
        }
    }//GEN-LAST:event_actualizarLibMenuItemActionPerformed

    private void devolverLibMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_devolverLibMenuItemActionPerformed
        if (!devolucionLibroView.isVisible()) {
            desktopPane.remove(devolucionLibroView);
            devolucionLibroView.setVisible(true);
            desktopPane.add(devolucionLibroView);
        }
    }//GEN-LAST:event_devolverLibMenuItemActionPerformed

    private void registrarUsuMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarUsuMenuItemActionPerformed
        if (!registrarUsuarioView.isVisible()) {
            desktopPane.remove(registrarUsuarioView);
            registrarUsuarioView.setVisible(true);
            desktopPane.add(registrarUsuarioView);
        }
    }//GEN-LAST:event_registrarUsuMenuItemActionPerformed

    private void actualizarUsuMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarUsuMenuItemActionPerformed
        if (!actualizarRegistrarUsuarioView.isVisible()) {
            desktopPane.remove(actualizarRegistrarUsuarioView);
            actualizarRegistrarUsuarioView.setVisible(true);
            desktopPane.add(actualizarRegistrarUsuarioView);
        }
    }//GEN-LAST:event_actualizarUsuMenuItemActionPerformed

    private void prestamoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prestamoMenuItemActionPerformed
        if (!registrarPrestamoView.isVisible()) {
            desktopPane.remove(registrarPrestamoView);
            registrarPrestamoView.setVisible(true);
            desktopPane.add(registrarPrestamoView);
        }
    }//GEN-LAST:event_prestamoMenuItemActionPerformed

    private void gestionLibrosMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionLibrosMenuItemActionPerformed
        if (!listaLibrosView.isVisible()) {
            desktopPane.remove(listaLibrosView);
            listaLibrosView.setVisible(true);
            desktopPane.add(listaLibrosView);
        }
    }//GEN-LAST:event_gestionLibrosMenuItemActionPerformed

    private void gestionUsuMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionUsuMenuItemActionPerformed
        if (!listaUsuariosView.isVisible()) {
            desktopPane.remove(listaUsuariosView);
            listaUsuariosView.setVisible(true);
            desktopPane.add(listaUsuariosView);
        }
    }//GEN-LAST:event_gestionUsuMenuItemActionPerformed

    private void gestionPrestamosMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionPrestamosMenuItemActionPerformed
        if (!listaPrestamosView.isVisible()) {
            desktopPane.remove(listaPrestamosView);
            listaPrestamosView.setVisible(true);
            desktopPane.add(listaPrestamosView);
        }    }//GEN-LAST:event_gestionPrestamosMenuItemActionPerformed

    private void registrarAutorLibMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarAutorLibMenuItemActionPerformed
        if (!registrarAutorView.isVisible()) {
            desktopPane.remove(registrarAutorView);
            registrarAutorView.setVisible(true);
            desktopPane.add(registrarAutorView);
        }
    }//GEN-LAST:event_registrarAutorLibMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try {
            com.formdev.flatlaf.FlatDarkLaf.setup();
        } catch (Exception ex) {
            System.err.println("Error al iniciar FlatLaf");
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem actualizarLibMenuItem;
    private javax.swing.JMenuItem actualizarUsuMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem devolverLibMenuItem;
    private javax.swing.JMenuItem gestionLibrosMenuItem;
    private javax.swing.JMenu gestionMenu;
    private javax.swing.JMenuItem gestionPrestamosMenuItem;
    private javax.swing.JMenuItem gestionUsuMenuItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu libroMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu prestamoMenu;
    private javax.swing.JMenuItem prestamoMenuItem;
    private javax.swing.JMenuItem registrarAutorLibMenuItem;
    private javax.swing.JMenuItem registrarLibMenuItem;
    private javax.swing.JMenuItem registrarUsuMenuItem;
    private javax.swing.JMenu usuarioMenu;
    // End of variables declaration//GEN-END:variables

}
