/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.biblioteca.views;

/**
 *
 * @author DELL
 */
public class RegistrarLibroView extends javax.swing.JInternalFrame {

    /**
     * Creates new form RegistrarLibroView
     */
    public RegistrarLibroView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCategoria = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        lblAnio = new javax.swing.JLabel();
        txtISBN = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        txtAnio = new javax.swing.JTextField();
        lblISBN = new javax.swing.JLabel();
        lblAutor = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        lblCategoria = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Registrar Libro");
        setPreferredSize(new java.awt.Dimension(550, 420));

        jPanel1.setBackground(new java.awt.Color(35, 30, 25));
        jPanel1.setPreferredSize(new java.awt.Dimension(363, 488));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel2.setBackground(new java.awt.Color(35, 30, 25));

        jLabel1.setBackground(new java.awt.Color(218, 204, 184));
        jLabel1.setFont(new java.awt.Font("Serif", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(218, 204, 184));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/biblioteca/images/libro-circular-abierto (2).png"))); // NOI18N
        jLabel1.setText("Registre su Libro");
        jLabel1.setIconTextGap(10);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/biblioteca/images/Adobe Express - file.png"))); // NOI18N
        jLabel2.setText("dwdw");

        txtCategoria.setBackground(new java.awt.Color(18, 19, 17));
        txtCategoria.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        txtCategoria.setForeground(new java.awt.Color(218, 204, 184));
        txtCategoria.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 40, 28)));
        txtCategoria.setCaretColor(new java.awt.Color(51, 204, 0));

        jComboBox1.setBackground(new java.awt.Color(18, 19, 17));
        jComboBox1.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(218, 204, 184));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 40, 28)));

        lblAnio.setBackground(new java.awt.Color(218, 204, 184));
        lblAnio.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        lblAnio.setForeground(new java.awt.Color(218, 204, 184));
        lblAnio.setText("Año:");

        txtISBN.setBackground(new java.awt.Color(18, 19, 17));
        txtISBN.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        txtISBN.setForeground(new java.awt.Color(218, 204, 184));
        txtISBN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 40, 28)));
        txtISBN.addActionListener(this::txtISBNActionPerformed);

        btnAceptar.setBackground(new java.awt.Color(209, 161, 95));
        btnAceptar.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        btnAceptar.setForeground(new java.awt.Color(0, 0, 0));
        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/biblioteca/images/controlar (2).png"))); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.setBorderPainted(false);
        btnAceptar.setFocusPainted(false);
        btnAceptar.setIconTextGap(10);
        btnAceptar.addActionListener(this::btnAceptarActionPerformed);

        txtAnio.setBackground(new java.awt.Color(18, 19, 17));
        txtAnio.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        txtAnio.setForeground(new java.awt.Color(218, 204, 184));
        txtAnio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 40, 28)));

        lblISBN.setBackground(new java.awt.Color(218, 204, 184));
        lblISBN.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        lblISBN.setForeground(new java.awt.Color(218, 204, 184));
        lblISBN.setText("ISBN:");

        lblAutor.setBackground(new java.awt.Color(218, 204, 184));
        lblAutor.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        lblAutor.setForeground(new java.awt.Color(218, 204, 184));
        lblAutor.setText("Autor:");

        txtTitulo.setBackground(new java.awt.Color(18, 19, 17));
        txtTitulo.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        txtTitulo.setForeground(new java.awt.Color(218, 204, 184));
        txtTitulo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 40, 28)));

        lblCategoria.setBackground(new java.awt.Color(218, 204, 184));
        lblCategoria.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        lblCategoria.setForeground(new java.awt.Color(218, 204, 184));
        lblCategoria.setText("Categoria:");

        btnCancelar.setBackground(new java.awt.Color(49, 43, 35));
        btnCancelar.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(235, 235, 235));
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/biblioteca/images/deshacer.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorderPainted(false);
        btnCancelar.setFocusPainted(false);
        btnCancelar.setIconTextGap(8);
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        lblTitulo.setBackground(new java.awt.Color(218, 204, 184));
        lblTitulo.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(218, 204, 184));
        lblTitulo.setText("Titulo:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblISBN)
                                    .addComponent(lblTitulo)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCategoria)
                                    .addComponent(lblAutor)
                                    .addComponent(lblAnio)))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtISBN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(btnAceptar)
                .addGap(18, 18, 18)
                .addComponent(btnCancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblISBN)
                .addGap(12, 12, 12)
                .addComponent(txtISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblAutor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblAnio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCategoria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(btnCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 18, 32, 32);
        jPanel1.add(jPanel2, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtISBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtISBNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtISBNActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblAnio;
    private javax.swing.JLabel lblAutor;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblISBN;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtAnio;
    private javax.swing.JTextField txtCategoria;
    private javax.swing.JTextField txtISBN;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
